services:
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true

    App\CartContext\Domain\Repository\CartRepositoryInterface:
        alias: App\CartContext\Infrastructure\Persistence\Doctrine\DoctrineCartRepository
    App\OrderContext\Domain\Repository\OrderRepositoryInterface:
        alias: App\OrderContext\Infrastructure\Persistence\Doctrine\DoctrineOrderRepository
